const chapter=document.getElementById('chapter');let lang='en';
const chapters={tech:{number:'01 / TECHNOLOGY',en:['A different way of seeing.','At Huddly, I work with AI cameras that help people meet and collaborate. It brings together the things I love about technology: understanding a difficult problem, building something tangible, and seeing it work in the real world.','My background is in computer science and software. My curiosity tends to wander across the boundaries.'],no:['En annen måte å se på.','I Huddly jobber jeg med AI-kameraer som hjelper mennesker å møtes og samarbeide. Det forener det jeg liker best med teknologi: å forstå et vanskelig problem, bygge noe håndfast og se det fungere i praksis.','Bakgrunnen min er informatikk og programvare. Nysgjerrigheten holder seg sjelden innenfor faggrensene.']},music:{number:'02 / MUSIC',en:['Room for improvisation.','Jazz piano has its own kind of conversation: listening, responding, leaving room, and occasionally taking a chance you haven’t quite thought through.','I studied jazz as well as technology. Music remains a constant — at the keyboard, in a band, or simply listening closely to a good record.'],no:['Rom for improvisasjon.','Jazzpiano er en egen samtaleform: å lytte, svare, gi plass og av og til ta en sjanse du ikke helt har tenkt gjennom.','Jeg har studert både jazz og teknologi. Musikken er alltid med — ved tangentene, i et band eller når jeg lytter til en god plate.']},sea:{number:'03 / SAILING',en:['Somewhere beyond the shore.','Billie’s Holiday is my Jeanneau Sun Odyssey 410. Sailing her is a chance to trade meetings and screens for weather, water and a different sense of time.','The Scandinavian coast offers more than enough reasons to take the long way. A sheltered harbour, an open crossing, and the next place just over the horizon.'],no:['Et sted utenfor land.','Billie’s Holiday er min Jeanneau Sun Odyssey 410. Om bord byttes møter og skjermer ut med vær, vann og en annen opplevelse av tid.','Den skandinaviske kysten gir mer enn nok grunner til å ta den lange veien. En lun havn, en åpen overfart og neste sted rett over horisonten.']},road:{number:'04 / MOTORCYCLES',en:['The journey is the point.','My bike is a Harley-Davidson Road King. An excuse to get out, find a road worth following, and enjoy everything between departure and arrival.','I like the change of perspective that comes with travelling on two wheels. You notice the landscape — and you certainly notice the weather.'],no:['Turen er poenget.','Jeg kjører en Harley-Davidson Road King. En god grunn til å komme seg ut, finne en vei det er verdt å følge og nyte det som skjer mellom avreise og ankomst.','På to hjul får man et annet perspektiv. Man legger merke til landskapet — og definitivt til været.']}};
function closeChapter(){chapter.close();document.body.style.overflow=''}
document.querySelectorAll('[data-world]').forEach(b=>b.addEventListener('click',()=>{const c=chapters[b.dataset.world],t=c[lang];document.getElementById('chapter-number').textContent=c.number;document.getElementById('chapter-title').textContent=t[0];const box=document.getElementById('chapter-text');box.replaceChildren(...t.slice(1).map(text=>{const p=document.createElement('p');p.textContent=text;return p}));chapter.showModal();document.body.style.overflow='hidden'}));
chapter.querySelector('.close').addEventListener('click',closeChapter);chapter.querySelector('.chapter-done').addEventListener('click',closeChapter);chapter.addEventListener('close',()=>document.body.style.overflow='');chapter.addEventListener('click',e=>{if(e.target===chapter){const r=chapter.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeChapter()}});
document.getElementById('language').addEventListener('click',()=>{lang=lang==='en'?'no':'en';document.documentElement.lang=lang==='no'?'nb':'en';document.querySelectorAll('[data-en]').forEach(el=>el.innerHTML=el.dataset[lang]);const b=document.getElementById('language');b.textContent=lang==='en'?'NO':'EN';b.setAttribute('aria-label',lang==='en'?'Switch to Norwegian':'Switch to English');document.dispatchEvent(new Event('languagechange'))});document.getElementById('year').textContent=new Date().getFullYear();

const photos=[
{id:'water',title:'Salt water & blue skies',alt:'Portrait aboard a sailboat, wearing mirrored blue sunglasses'},
{id:'road',title:'The long way round',alt:'A motorcycle stop beside a misty coastal arch bridge'},
{id:'sound',title:'A little more volume',alt:'Stacks of grey, blue and yellow loudspeakers'},
{id:'sail',title:'Under sail',alt:'Portrait beneath a white sail against blue sky'},
{id:'bridge',title:'Lines across the water',alt:'A long bridge stretching over the sea'},
{id:'street',title:'A different kind of gallery',alt:'Portrait in a street lined with colourful graffiti'},
{id:'party',title:'An occasion worth dressing for',alt:'Portrait in a checked jacket in front of golden streamers'},
{id:'sunset',title:'Last light',alt:'Golden sunset over water and sailboat masts'},
{id:'city',title:'A change of scenery',alt:'Portrait by a canal lined with historic buildings'},
{id:'coast',title:'Somewhere along the coast',alt:'Portrait on a green hillside overlooking the sea'}];
const wall=document.getElementById('photo-wall');photos.forEach((p,i)=>{const b=document.createElement('button');b.dataset.photo=p.id;b.style.setProperty('--r',`${[3,-4,2,-2,4,-3][i%6]}deg`);b.setAttribute('aria-label',`Open photograph: ${p.title}`);const im=document.createElement('img');im.src=`photos/${p.id}.jpg`;im.alt=p.alt;im.loading='lazy';const c=document.createElement('span');c.textContent=`${String(i+1).padStart(2,'0')} / ${p.title.toUpperCase()}`;b.append(im,c);wall.append(b)});
const lightbox=document.getElementById('lightbox');let selected=0;
function showPhoto(index){selected=(index+photos.length)%photos.length;const p=photos[selected],im=document.getElementById('lightbox-image');im.src=`photos/${p.id}.jpg`;im.alt=p.alt;document.getElementById('lightbox-caption').textContent=`${selected+1} / ${photos.length} — ${p.title}`}
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{showPhoto(photos.findIndex(p=>p.id===b.dataset.photo));lightbox.showModal();document.body.style.overflow='hidden'}));
lightbox.querySelector('.close').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('close',()=>document.body.style.overflow='');document.getElementById('previous').addEventListener('click',()=>showPhoto(selected-1));document.getElementById('next').addEventListener('click',()=>showPhoto(selected+1));lightbox.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();showPhoto(selected-1)}if(e.key==='ArrowRight'){e.preventDefault();showPhoto(selected+1)}});lightbox.addEventListener('click',e=>{if(e.target===lightbox){const r=lightbox.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)lightbox.close()}});
